// Generated by dts-bundle-generator v9.5.1

import p5Class from 'p5';

declare const logLevels: {
	DEBUG: number;
	INFO: number;
	WARN: number;
	ERROR: number;
	FATAL: number;
	SIGINT: number;
};
export type LogLevel = keyof typeof logLevels;
export type Message = string;
export type MessageParams = {
	msg: Message;
	/** Whether to generate an standard error after a log message. */
	throw?: boolean;
	/** Extra data to log after a log message. */
	data?: unknown;
	/**
	 * Whether to stringify extra data. Has no effect if data is undefined.
	 *
	 * Uses `JSON.stringify(data, null, 4)`.
	 */
	stringifyData?: boolean;
};
/** Type for the message argument. */
export type MessageOrParams = Message | MessageParams;
export declare class Logger {
	private get logPrefixes();
	private set logPrefixes(value);
	private _logPrefixes;
	get logPrefix(): string | null;
	private set logPrefix(value);
	private _logPrefix;
	private get messagePaddings();
	private set messagePaddings(value);
	private _messagePaddings;
	get messagePad(): string | null;
	private set messagePad(value);
	private _messagePad;
	constructor(...logPrefixes: string[]);
	/** Set global log level. */
	static setLogLevel(level: LogLevel): void;
	/** Get current log level. */
	static getLogLevel(): LogLevel;
	/** Sets instance log prefixes. */
	setLogPrefixes: (...prefixes: string[]) => this;
	/** Appends a log prefix to the instance. */
	appendLogPrefix: (prefix: string) => this;
	/**
	 * Adds a specified padding string before each message (but after prefix). Can accumulate.
	 *
	 * - Call {@link removeAllMessagePadding} to reset all added padding.
	 * - Call {@link removeLastMessagePadding} to reset last added padding.
	 */
	addMessagePadding: (padding: string) => this;
	/** Removes all message padding. */
	removeAllMessagePadding: () => this;
	/** Removes last added message padding. */
	removeLastMessagePadding: () => this;
	clone(): Logger;
	log: (level: LogLevel, messageOrParams: MessageOrParams, ...extraMessages: unknown[]) => void;
	logDebug: (messageOrParams: MessageOrParams, ...extraMessages: unknown[]) => void;
	logInfo: (messageOrParams: MessageOrParams, ...extraMessages: unknown[]) => void;
	logWarn: (messageOrParams: MessageOrParams, ...extraMessages: unknown[]) => void;
	logError: (messageOrParams: MessageOrParams, ...extraMessages: unknown[]) => void;
	logFatal: (messageOrParams: MessageOrParams, ...extraMessages: unknown[]) => void;
	logFatalAndThrow: (messageOrParams: Message | Omit<MessageParams, "throw">, ...extraMessages: unknown[]) => never;
}
export declare class Client {
	private requestsTimeoutMs;
	private imageExtension;
	private serverUrl;
	private framesSavedCounter;
	private getBlob;
	private isInit;
	init(p5: p5Class, opts?: Partial<{
		/**
		 * Port that the server uses.
		 *
		 * @default
		 * 3420
		 */
		serverPort: number;
		/**
		 * Frame image file extension.
		 *
		 * @default
		 * png
		 */
		imageExtension: string;
		/**
		 * Timeout in ms for any request to the server.
		 *
		 * @default
		 * 60000 (60 sec)
		 */
		requestTimeoutMs: number;
		/**
		 * Log level for every instance.
		 *
		 * @default
		 * INFO
		 */
		logLevel: LogLevel;
	}>): Promise<void>;
	/**
	 * Saves current frame.
	 *
	 * **Note: this must be called at the end of a drawing loop.**
	 * Internally, the execution is "paused" by calling `noLoop()`, capturing the frame, and resuming with `loop()`.
	 * This is needed due to P5 not being able to run asynchronous code in it's `draw()` call.
	 * @param p5 P5 instance.
	 * @param imageExtension Extension to save the image with.
	 * @returns
	 */
	saveFrame(): Promise<void>;
	signalNewBatch(): Promise<void>;
	endBatch(): Promise<void>;
	/**
	 * Send message to Server and receive a response message.
	 * @param message Message to send.
	 * @param timeoutMs Request timeout. After it passes, the request is canceled and error is thrown.
	 * @returns Server message response.
	 */
	private sendMessage;
	/** Resolves when server frees and ready for further processing. */
	private waitServerFree;
	private assertInit;
	private assertServerAlive;
}

export {
	Client as default,
};

export {};
